name: Data Sync

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  sync-job:
    runs-on: ubuntu-22.04
    steps:
      #
      #   Setup
      #
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      #
      #   Extract
      #
      - name: Extract
        run: |
          pip3 install -r requirements.txt
          python3 extract_channel.py
          python3 extract_channel_replays.py
          python3 channel_with_replays.py

      - name: Revision
        run: |
          git config --local user.email "violet.dev.master.bot@gmail.com"
          git config --local user.name "violet-dev-bot"
          git config --global pull.rebase false
          git add web/public/
          git commit -m "Data Sync"
          git pull

      - name: Push
        id: trypush
        uses: ad-m/github-push-action@master
        with:
          branch: "main"
          github_token: $
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypush.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 1
        id: trypushfs1
        if: ${{ failure() && steps.trypush.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: "master"
          github_token: $
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs1.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 2
        id: trypushfs2
        if: ${{ failure() && steps.trypushfs1.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: "master"
          github_token: $
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs2.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 3
        id: trypushfs3
        if: ${{ failure() && steps.trypushfs2.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: "master"
          github_token: $
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs3.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 4
        id: trypushfs4
        if: ${{ failure() && steps.trypushfs3.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: "master"
          github_token: $
      - name: Fail Safe Pull
        if: ${{ failure() && steps.trypushfs4.outcome == 'failure' }}
        run: git pull
      - name: Fail Safe 5
        if: ${{ failure() && steps.trypushfs4.outcome == 'failure' }}
        uses: ad-m/github-push-action@master
        with:
          branch: "master"
          github_token: $
